# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: 
    npm install -g @vue/cli
    npm install
    npm run build ----output-path='/home/vsts/work/1/s/dist/'
  displayName: 'npm install and build'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '/home/vsts/work/1/s/dist/'
    artifact: 'dist'